service: notifyengage-backend
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  httpApi:
    cors: true
  environment:
    MONGO_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}

functions:
  signup:
    handler: functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: post

  login:
    handler: functions/login.handler
    events:
      - httpApi:
          path: /login
          method: post

  getNotifications:
    handler: functions/getNotifications.handler
    events:
      - httpApi:
          path: /notifications
          method: get

  postNotification:
    handler: functions/postNotification.handler
    events:
      - httpApi:
          path: /notifications
          method: post

  deleteNotification:
    handler: functions/deleteNotification.handler
    events:
      - httpApi:
          path: /notifications/{id}
          method: delete

plugins:
  - serverless-offline
