service: notifyengage-backend

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1 
  environment:
    MONGO_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    PORT: ${env:PORT}

functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - .git/**